<?php
/**
 * Asset
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ServiceM8 API
 *
 * Move your app forward with the ServiceM8 API    ## Limits and Throttling To ensure continuous quality of service, API usage can be subject to throttling. The throttle will be applied once an API consumer reaches a certain  threshold in terms of a maximum number of requests per minute. Most clients will never hit this threshold, but those that do, will get met by a  HTTP 429 Too Many Requests response code.    There is a limit of 180 requests per minute, if you reach this you will receive a HTTP 429 with a text body of \"Number of allowed API requests per minute exceeded\". There is a limit of 20000 requests per day, if you reach this you will receive a HTTP 429 with a text body of \"Number of allowed API requests per day exceeded\".  We encourage all API developers to anticipate this error, and take appropriate measures like e.g. using a cached value from a previous call, or passing on a message to the end user that gets subjected to this behaviour (if any).  Limits are per Addon per account.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Asset Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Asset implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Asset';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'uuid' => 'string',
        'active' => 'float',
        'editDate' => 'string',
        'companyUuid' => 'string',
        'assetCode' => 'string',
        'assetTypeUuid' => 'string',
        'name' => 'string',
        'lat' => 'float',
        'lng' => 'float',
        'geoTimestamp' => 'string',
        'altitude' => 'string',
        'fieldData' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'uuid' => 'uuid',
        'active' => null,
        'editDate' => null,
        'companyUuid' => 'uuid',
        'assetCode' => null,
        'assetTypeUuid' => 'uuid',
        'name' => null,
        'lat' => 'float',
        'lng' => 'float',
        'geoTimestamp' => null,
        'altitude' => null,
        'fieldData' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'uuid' => false,
		'active' => false,
		'editDate' => false,
		'companyUuid' => false,
		'assetCode' => false,
		'assetTypeUuid' => false,
		'name' => false,
		'lat' => false,
		'lng' => false,
		'geoTimestamp' => false,
		'altitude' => false,
		'fieldData' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'uuid' => 'uuid',
        'active' => 'active',
        'editDate' => 'edit_date',
        'companyUuid' => 'company_uuid',
        'assetCode' => 'asset_code',
        'assetTypeUuid' => 'asset_type_uuid',
        'name' => 'name',
        'lat' => 'lat',
        'lng' => 'lng',
        'geoTimestamp' => 'geo_timestamp',
        'altitude' => 'altitude',
        'fieldData' => 'field_data'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'uuid' => 'setUuid',
        'active' => 'setActive',
        'editDate' => 'setEditDate',
        'companyUuid' => 'setCompanyUuid',
        'assetCode' => 'setAssetCode',
        'assetTypeUuid' => 'setAssetTypeUuid',
        'name' => 'setName',
        'lat' => 'setLat',
        'lng' => 'setLng',
        'geoTimestamp' => 'setGeoTimestamp',
        'altitude' => 'setAltitude',
        'fieldData' => 'setFieldData'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'uuid' => 'getUuid',
        'active' => 'getActive',
        'editDate' => 'getEditDate',
        'companyUuid' => 'getCompanyUuid',
        'assetCode' => 'getAssetCode',
        'assetTypeUuid' => 'getAssetTypeUuid',
        'name' => 'getName',
        'lat' => 'getLat',
        'lng' => 'getLng',
        'geoTimestamp' => 'getGeoTimestamp',
        'altitude' => 'getAltitude',
        'fieldData' => 'getFieldData'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('uuid', $data ?? [], null);
        $this->setIfExists('active', $data ?? [], null);
        $this->setIfExists('editDate', $data ?? [], null);
        $this->setIfExists('companyUuid', $data ?? [], null);
        $this->setIfExists('assetCode', $data ?? [], null);
        $this->setIfExists('assetTypeUuid', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('lat', $data ?? [], null);
        $this->setIfExists('lng', $data ?? [], null);
        $this->setIfExists('geoTimestamp', $data ?? [], null);
        $this->setIfExists('altitude', $data ?? [], null);
        $this->setIfExists('fieldData', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets uuid
     *
     * @return string|null
     */
    public function getUuid()
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     *
     * @param string|null $uuid Record UUID key
     *
     * @return self
     */
    public function setUuid($uuid)
    {

        if (is_null($uuid)) {
            throw new \InvalidArgumentException('non-nullable uuid cannot be null');
        }

        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets active
     *
     * @return float|null
     */
    public function getActive()
    {
        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param float|null $active Record active/deleted flag.   Valid values are [0,1]
     *
     * @return self
     */
    public function setActive($active)
    {

        if (is_null($active)) {
            throw new \InvalidArgumentException('non-nullable active cannot be null');
        }

        $this->container['active'] = $active;

        return $this;
    }

    /**
     * Gets editDate
     *
     * @return string|null
     */
    public function getEditDate()
    {
        return $this->container['editDate'];
    }

    /**
     * Sets editDate
     *
     * @param string|null $editDate Record last modified timestamp
     *
     * @return self
     */
    public function setEditDate($editDate)
    {

        if (is_null($editDate)) {
            throw new \InvalidArgumentException('non-nullable editDate cannot be null');
        }

        $this->container['editDate'] = $editDate;

        return $this;
    }

    /**
     * Gets companyUuid
     *
     * @return string|null
     */
    public function getCompanyUuid()
    {
        return $this->container['companyUuid'];
    }

    /**
     * Sets companyUuid
     *
     * @param string|null $companyUuid companyUuid
     *
     * @return self
     */
    public function setCompanyUuid($companyUuid)
    {

        if (is_null($companyUuid)) {
            throw new \InvalidArgumentException('non-nullable companyUuid cannot be null');
        }

        $this->container['companyUuid'] = $companyUuid;

        return $this;
    }

    /**
     * Gets assetCode
     *
     * @return string|null
     */
    public function getAssetCode()
    {
        return $this->container['assetCode'];
    }

    /**
     * Sets assetCode
     *
     * @param string|null $assetCode assetCode
     *
     * @return self
     */
    public function setAssetCode($assetCode)
    {

        if (is_null($assetCode)) {
            throw new \InvalidArgumentException('non-nullable assetCode cannot be null');
        }

        $this->container['assetCode'] = $assetCode;

        return $this;
    }

    /**
     * Gets assetTypeUuid
     *
     * @return string|null
     */
    public function getAssetTypeUuid()
    {
        return $this->container['assetTypeUuid'];
    }

    /**
     * Sets assetTypeUuid
     *
     * @param string|null $assetTypeUuid assetTypeUuid
     *
     * @return self
     */
    public function setAssetTypeUuid($assetTypeUuid)
    {

        if (is_null($assetTypeUuid)) {
            throw new \InvalidArgumentException('non-nullable assetTypeUuid cannot be null');
        }

        $this->container['assetTypeUuid'] = $assetTypeUuid;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {

        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets lat
     *
     * @return float|null
     */
    public function getLat()
    {
        return $this->container['lat'];
    }

    /**
     * Sets lat
     *
     * @param float|null $lat lat
     *
     * @return self
     */
    public function setLat($lat)
    {

        if (is_null($lat)) {
            throw new \InvalidArgumentException('non-nullable lat cannot be null');
        }

        $this->container['lat'] = $lat;

        return $this;
    }

    /**
     * Gets lng
     *
     * @return float|null
     */
    public function getLng()
    {
        return $this->container['lng'];
    }

    /**
     * Sets lng
     *
     * @param float|null $lng lng
     *
     * @return self
     */
    public function setLng($lng)
    {

        if (is_null($lng)) {
            throw new \InvalidArgumentException('non-nullable lng cannot be null');
        }

        $this->container['lng'] = $lng;

        return $this;
    }

    /**
     * Gets geoTimestamp
     *
     * @return string|null
     */
    public function getGeoTimestamp()
    {
        return $this->container['geoTimestamp'];
    }

    /**
     * Sets geoTimestamp
     *
     * @param string|null $geoTimestamp geoTimestamp
     *
     * @return self
     */
    public function setGeoTimestamp($geoTimestamp)
    {

        if (is_null($geoTimestamp)) {
            throw new \InvalidArgumentException('non-nullable geoTimestamp cannot be null');
        }

        $this->container['geoTimestamp'] = $geoTimestamp;

        return $this;
    }

    /**
     * Gets altitude
     *
     * @return string|null
     */
    public function getAltitude()
    {
        return $this->container['altitude'];
    }

    /**
     * Sets altitude
     *
     * @param string|null $altitude altitude
     *
     * @return self
     */
    public function setAltitude($altitude)
    {

        if (is_null($altitude)) {
            throw new \InvalidArgumentException('non-nullable altitude cannot be null');
        }

        $this->container['altitude'] = $altitude;

        return $this;
    }

    /**
     * Gets fieldData
     *
     * @return string|null
     */
    public function getFieldData()
    {
        return $this->container['fieldData'];
    }

    /**
     * Sets fieldData
     *
     * @param string|null $fieldData fieldData
     *
     * @return self
     */
    public function setFieldData($fieldData)
    {

        if (is_null($fieldData)) {
            throw new \InvalidArgumentException('non-nullable fieldData cannot be null');
        }

        $this->container['fieldData'] = $fieldData;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


