<?php
/**
 * Form
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ServiceM8 API
 *
 * Move your app forward with the ServiceM8 API    ## Limits and Throttling To ensure continuous quality of service, API usage can be subject to throttling. The throttle will be applied once an API consumer reaches a certain  threshold in terms of a maximum number of requests per minute. Most clients will never hit this threshold, but those that do, will get met by a  HTTP 429 Too Many Requests response code.    There is a limit of 180 requests per minute, if you reach this you will receive a HTTP 429 with a text body of \"Number of allowed API requests per minute exceeded\". There is a limit of 20000 requests per day, if you reach this you will receive a HTTP 429 with a text body of \"Number of allowed API requests per day exceeded\".  We encourage all API developers to anticipate this error, and take appropriate measures like e.g. using a cached value from a previous call, or passing on a message to the end user that gets subjected to this behaviour (if any).  Limits are per Addon per account.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Form Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Form implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Form';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'uuid' => 'string',
        'active' => 'float',
        'editDate' => 'string',
        'name' => 'string',
        'documentTemplateUuid' => 'string',
        'canBeUsedIndependently' => 'string',
        'badgeMandatoryState' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'uuid' => 'uuid',
        'active' => null,
        'editDate' => null,
        'name' => null,
        'documentTemplateUuid' => 'uuid',
        'canBeUsedIndependently' => null,
        'badgeMandatoryState' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'uuid' => 'uuid',
        'active' => 'active',
        'editDate' => 'edit_date',
        'name' => 'name',
        'documentTemplateUuid' => 'document_template_uuid',
        'canBeUsedIndependently' => 'can_be_used_independently',
        'badgeMandatoryState' => 'badge_mandatory_state'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'uuid' => 'setUuid',
        'active' => 'setActive',
        'editDate' => 'setEditDate',
        'name' => 'setName',
        'documentTemplateUuid' => 'setDocumentTemplateUuid',
        'canBeUsedIndependently' => 'setCanBeUsedIndependently',
        'badgeMandatoryState' => 'setBadgeMandatoryState'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'uuid' => 'getUuid',
        'active' => 'getActive',
        'editDate' => 'getEditDate',
        'name' => 'getName',
        'documentTemplateUuid' => 'getDocumentTemplateUuid',
        'canBeUsedIndependently' => 'getCanBeUsedIndependently',
        'badgeMandatoryState' => 'getBadgeMandatoryState'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['uuid'] = isset($data['uuid']) ? $data['uuid'] : null;
        $this->container['active'] = isset($data['active']) ? $data['active'] : null;
        $this->container['editDate'] = isset($data['editDate']) ? $data['editDate'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['documentTemplateUuid'] = isset($data['documentTemplateUuid']) ? $data['documentTemplateUuid'] : null;
        $this->container['canBeUsedIndependently'] = isset($data['canBeUsedIndependently']) ? $data['canBeUsedIndependently'] : null;
        $this->container['badgeMandatoryState'] = isset($data['badgeMandatoryState']) ? $data['badgeMandatoryState'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets uuid
     *
     * @return string|null
     */
    public function getUuid()
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     *
     * @param string|null $uuid Record UUID key
     *
     * @return $this
     */
    public function setUuid($uuid)
    {
        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets active
     *
     * @return float|null
     */
    public function getActive()
    {
        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param float|null $active Record active/deleted flag.   Valid values are [0,1]
     *
     * @return $this
     */
    public function setActive($active)
    {
        $this->container['active'] = $active;

        return $this;
    }

    /**
     * Gets editDate
     *
     * @return string|null
     */
    public function getEditDate()
    {
        return $this->container['editDate'];
    }

    /**
     * Sets editDate
     *
     * @param string|null $editDate Record last modified timestamp
     *
     * @return $this
     */
    public function setEditDate($editDate)
    {
        $this->container['editDate'] = $editDate;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets documentTemplateUuid
     *
     * @return string|null
     */
    public function getDocumentTemplateUuid()
    {
        return $this->container['documentTemplateUuid'];
    }

    /**
     * Sets documentTemplateUuid
     *
     * @param string|null $documentTemplateUuid documentTemplateUuid
     *
     * @return $this
     */
    public function setDocumentTemplateUuid($documentTemplateUuid)
    {
        $this->container['documentTemplateUuid'] = $documentTemplateUuid;

        return $this;
    }

    /**
     * Gets canBeUsedIndependently
     *
     * @return string|null
     */
    public function getCanBeUsedIndependently()
    {
        return $this->container['canBeUsedIndependently'];
    }

    /**
     * Sets canBeUsedIndependently
     *
     * @param string|null $canBeUsedIndependently canBeUsedIndependently
     *
     * @return $this
     */
    public function setCanBeUsedIndependently($canBeUsedIndependently)
    {
        $this->container['canBeUsedIndependently'] = $canBeUsedIndependently;

        return $this;
    }

    /**
     * Gets badgeMandatoryState
     *
     * @return string|null
     */
    public function getBadgeMandatoryState()
    {
        return $this->container['badgeMandatoryState'];
    }

    /**
     * Sets badgeMandatoryState
     *
     * @param string|null $badgeMandatoryState badgeMandatoryState
     *
     * @return $this
     */
    public function setBadgeMandatoryState($badgeMandatoryState)
    {
        $this->container['badgeMandatoryState'] = $badgeMandatoryState;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


