<?php
/**
 * Material
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ServiceM8 API
 *
 * Move your app forward with the ServiceM8 API    ## Limits and Throttling To ensure continuous quality of service, API usage can be subject to throttling. The throttle will be applied once an API consumer reaches a certain  threshold in terms of a maximum number of requests per minute. Most clients will never hit this threshold, but those that do, will get met by a  HTTP 429 Too Many Requests response code.    There is a limit of 180 requests per minute, if you reach this you will receive a HTTP 429 with a text body of \"Number of allowed API requests per minute exceeded\". There is a limit of 20000 requests per day, if you reach this you will receive a HTTP 429 with a text body of \"Number of allowed API requests per day exceeded\".  We encourage all API developers to anticipate this error, and take appropriate measures like e.g. using a cached value from a previous call, or passing on a message to the end user that gets subjected to this behaviour (if any).  Limits are per Addon per account.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Material Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Material implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Material';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'uuid' => 'string',
        'active' => 'float',
        'editDate' => 'string',
        'name' => 'string',
        'itemNumber' => 'string',
        'price' => 'string',
        'cost' => 'string',
        'itemDescription' => 'string',
        'quantityInStock' => 'float',
        'priceIncludesTaxes' => 'float',
        'useDescriptionForInvoicing' => 'string',
        'taxRateUuid' => 'string',
        'barcode' => 'string',
        'itemIsInventoried' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'uuid' => 'uuid',
        'active' => null,
        'editDate' => null,
        'name' => null,
        'itemNumber' => null,
        'price' => null,
        'cost' => null,
        'itemDescription' => null,
        'quantityInStock' => null,
        'priceIncludesTaxes' => null,
        'useDescriptionForInvoicing' => null,
        'taxRateUuid' => 'uuid',
        'barcode' => null,
        'itemIsInventoried' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'uuid' => 'uuid',
        'active' => 'active',
        'editDate' => 'edit_date',
        'name' => 'name',
        'itemNumber' => 'item_number',
        'price' => 'price',
        'cost' => 'cost',
        'itemDescription' => 'item_description',
        'quantityInStock' => 'quantity_in_stock',
        'priceIncludesTaxes' => 'price_includes_taxes',
        'useDescriptionForInvoicing' => 'use_description_for_invoicing',
        'taxRateUuid' => 'tax_rate_uuid',
        'barcode' => 'barcode',
        'itemIsInventoried' => 'item_is_inventoried'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'uuid' => 'setUuid',
        'active' => 'setActive',
        'editDate' => 'setEditDate',
        'name' => 'setName',
        'itemNumber' => 'setItemNumber',
        'price' => 'setPrice',
        'cost' => 'setCost',
        'itemDescription' => 'setItemDescription',
        'quantityInStock' => 'setQuantityInStock',
        'priceIncludesTaxes' => 'setPriceIncludesTaxes',
        'useDescriptionForInvoicing' => 'setUseDescriptionForInvoicing',
        'taxRateUuid' => 'setTaxRateUuid',
        'barcode' => 'setBarcode',
        'itemIsInventoried' => 'setItemIsInventoried'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'uuid' => 'getUuid',
        'active' => 'getActive',
        'editDate' => 'getEditDate',
        'name' => 'getName',
        'itemNumber' => 'getItemNumber',
        'price' => 'getPrice',
        'cost' => 'getCost',
        'itemDescription' => 'getItemDescription',
        'quantityInStock' => 'getQuantityInStock',
        'priceIncludesTaxes' => 'getPriceIncludesTaxes',
        'useDescriptionForInvoicing' => 'getUseDescriptionForInvoicing',
        'taxRateUuid' => 'getTaxRateUuid',
        'barcode' => 'getBarcode',
        'itemIsInventoried' => 'getItemIsInventoried'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['uuid'] = isset($data['uuid']) ? $data['uuid'] : null;
        $this->container['active'] = isset($data['active']) ? $data['active'] : null;
        $this->container['editDate'] = isset($data['editDate']) ? $data['editDate'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['itemNumber'] = isset($data['itemNumber']) ? $data['itemNumber'] : null;
        $this->container['price'] = isset($data['price']) ? $data['price'] : null;
        $this->container['cost'] = isset($data['cost']) ? $data['cost'] : null;
        $this->container['itemDescription'] = isset($data['itemDescription']) ? $data['itemDescription'] : null;
        $this->container['quantityInStock'] = isset($data['quantityInStock']) ? $data['quantityInStock'] : null;
        $this->container['priceIncludesTaxes'] = isset($data['priceIncludesTaxes']) ? $data['priceIncludesTaxes'] : null;
        $this->container['useDescriptionForInvoicing'] = isset($data['useDescriptionForInvoicing']) ? $data['useDescriptionForInvoicing'] : null;
        $this->container['taxRateUuid'] = isset($data['taxRateUuid']) ? $data['taxRateUuid'] : null;
        $this->container['barcode'] = isset($data['barcode']) ? $data['barcode'] : null;
        $this->container['itemIsInventoried'] = isset($data['itemIsInventoried']) ? $data['itemIsInventoried'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 70)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 70.";
        }

        if (!is_null($this->container['itemNumber']) && (mb_strlen($this->container['itemNumber']) > 30)) {
            $invalidProperties[] = "invalid value for 'itemNumber', the character length must be smaller than or equal to 30.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets uuid
     *
     * @return string
     */
    public function getUuid()
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     *
     * @param string $uuid Record UUID key
     *
     * @return $this
     */
    public function setUuid($uuid)
    {
        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets active
     *
     * @return float
     */
    public function getActive()
    {
        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param float $active Record active/deleted flag.   Valid values are [0,1]
     *
     * @return $this
     */
    public function setActive($active)
    {
        $this->container['active'] = $active;

        return $this;
    }

    /**
     * Gets editDate
     *
     * @return string
     */
    public function getEditDate()
    {
        return $this->container['editDate'];
    }

    /**
     * Sets editDate
     *
     * @param string $editDate Record last modified timestamp
     *
     * @return $this
     */
    public function setEditDate($editDate)
    {
        $this->container['editDate'] = $editDate;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        if ((mb_strlen($name) > 70)) {
            throw new \InvalidArgumentException('invalid length for $name when calling Material., must be smaller than or equal to 70.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets itemNumber
     *
     * @return string
     */
    public function getItemNumber()
    {
        return $this->container['itemNumber'];
    }

    /**
     * Sets itemNumber
     *
     * @param string $itemNumber itemNumber
     *
     * @return $this
     */
    public function setItemNumber($itemNumber)
    {
        if (!is_null($itemNumber) && (mb_strlen($itemNumber) > 30)) {
            throw new \InvalidArgumentException('invalid length for $itemNumber when calling Material., must be smaller than or equal to 30.');
        }

        $this->container['itemNumber'] = $itemNumber;

        return $this;
    }

    /**
     * Gets price
     *
     * @return string
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param string $price price
     *
     * @return $this
     */
    public function setPrice($price)
    {
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets cost
     *
     * @return string
     */
    public function getCost()
    {
        return $this->container['cost'];
    }

    /**
     * Sets cost
     *
     * @param string $cost cost
     *
     * @return $this
     */
    public function setCost($cost)
    {
        $this->container['cost'] = $cost;

        return $this;
    }

    /**
     * Gets itemDescription
     *
     * @return string
     */
    public function getItemDescription()
    {
        return $this->container['itemDescription'];
    }

    /**
     * Sets itemDescription
     *
     * @param string $itemDescription itemDescription
     *
     * @return $this
     */
    public function setItemDescription($itemDescription)
    {
        $this->container['itemDescription'] = $itemDescription;

        return $this;
    }

    /**
     * Gets quantityInStock
     *
     * @return float
     */
    public function getQuantityInStock()
    {
        return $this->container['quantityInStock'];
    }

    /**
     * Sets quantityInStock
     *
     * @param float $quantityInStock quantityInStock
     *
     * @return $this
     */
    public function setQuantityInStock($quantityInStock)
    {
        $this->container['quantityInStock'] = $quantityInStock;

        return $this;
    }

    /**
     * Gets priceIncludesTaxes
     *
     * @return float
     */
    public function getPriceIncludesTaxes()
    {
        return $this->container['priceIncludesTaxes'];
    }

    /**
     * Sets priceIncludesTaxes
     *
     * @param float $priceIncludesTaxes Valid values are [0,1]
     *
     * @return $this
     */
    public function setPriceIncludesTaxes($priceIncludesTaxes)
    {
        $this->container['priceIncludesTaxes'] = $priceIncludesTaxes;

        return $this;
    }

    /**
     * Gets useDescriptionForInvoicing
     *
     * @return string
     */
    public function getUseDescriptionForInvoicing()
    {
        return $this->container['useDescriptionForInvoicing'];
    }

    /**
     * Sets useDescriptionForInvoicing
     *
     * @param string $useDescriptionForInvoicing useDescriptionForInvoicing
     *
     * @return $this
     */
    public function setUseDescriptionForInvoicing($useDescriptionForInvoicing)
    {
        $this->container['useDescriptionForInvoicing'] = $useDescriptionForInvoicing;

        return $this;
    }

    /**
     * Gets taxRateUuid
     *
     * @return string
     */
    public function getTaxRateUuid()
    {
        return $this->container['taxRateUuid'];
    }

    /**
     * Sets taxRateUuid
     *
     * @param string $taxRateUuid taxRateUuid
     *
     * @return $this
     */
    public function setTaxRateUuid($taxRateUuid)
    {
        $this->container['taxRateUuid'] = $taxRateUuid;

        return $this;
    }

    /**
     * Gets barcode
     *
     * @return string
     */
    public function getBarcode()
    {
        return $this->container['barcode'];
    }

    /**
     * Sets barcode
     *
     * @param string $barcode barcode
     *
     * @return $this
     */
    public function setBarcode($barcode)
    {
        $this->container['barcode'] = $barcode;

        return $this;
    }

    /**
     * Gets itemIsInventoried
     *
     * @return float
     */
    public function getItemIsInventoried()
    {
        return $this->container['itemIsInventoried'];
    }

    /**
     * Sets itemIsInventoried
     *
     * @param float $itemIsInventoried Valid values are [0,1]
     *
     * @return $this
     */
    public function setItemIsInventoried($itemIsInventoried)
    {
        $this->container['itemIsInventoried'] = $itemIsInventoried;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


